# Tensorflow-Basics

####    Installation


pip3 install --upgrade tensorflow


In [1]:
import tensorflow as tf

print(tf.__version__)

1.3.0


#### Creating First Graph and Running It in  a Session

In [2]:
# The Graph will be as following 
# f = x*x*y + y + 2

x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x*x*y + y + 2

In [3]:
session = tf.Session()
session.run(x.initializer)
session.run(y.initializer)
result = session.run(f)
print(result)

42


#### Running Graph Inside The 'With' Block

In [4]:
with tf.Session() as session:
    x.initializer.run() # equivalent to calling tf.get_default_session().run(x.initializer)
    y.initializer.run()
    result = f.eval() # equivalent to calling tf.get_default_session().run(f)
    
    print(result)

42


#### Initialize Variables via tf.global_variables_initializer()

In [5]:
init = tf.global_variables_initializer()

with tf.Session() as session:
    init.run()
    result = f.eval()
    
    print(result)

42


#### Running Graph with Interactive Session

In [6]:
init = tf.global_variables_initializer()
session = tf.InteractiveSession()
init.run()
result = f.eval()

print(result)

session.close() # you have to close the session!

42


#### Managing Graphs

In [7]:
x1 = tf.Variable(1)
x1.graph is tf.get_default_graph()

True

In [8]:
graph = tf.Graph()

with graph.as_default():
    x2 = tf.Variable(2)

x2.graph is graph

True

In [9]:
x2.graph is tf.get_default_graph()

False

#### Lifecycle of a Node Value

In [10]:
# evaluates x and w twice
w = tf.constant(3)
x = w + 2
y = x + 5
z = x * 3

with tf.Session() as session:
    print(y.eval()) # 10
    print(z.eval()) # 15

10
15


In [11]:
# evaluates x and w once
with tf.Session() as session:
    y_val, z_val = session.run([y,z])
    print(y_val) # 10
    print(z_val) # 15

10
15


#### Linear Regression (W = (X.T * X)-1  *  X.T * y)

In [12]:
import numpy as np
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
m,n = housing.data.shape
data_with_bias = np.c_[np.ones((m,1)), housing.data]

X = tf.constant(data_with_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1,1) , dtype=tf.float32, name="y")
XT = tf.transpose(X)
W = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT,X)), XT), y)

with tf.Session() as session:
    value = W.eval()
    print(value)

[[-3.7465141e+01]
 [ 4.3573415e-01]
 [ 9.3382923e-03]
 [-1.0662201e-01]
 [ 6.4410698e-01]
 [-4.2513184e-06]
 [-3.7732250e-03]
 [-4.2664889e-01]
 [-4.4051403e-01]]


#### Tensorflow 'Constants'

In [14]:
hello = tf.constant("hello ")
world = tf.constant("World")
type(hello)
type(world)

tensorflow.python.framework.ops.Tensor

In [15]:
print(hello)

Tensor("Const_1:0", shape=(), dtype=string)


In [16]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [17]:
print(result)

b'hello World'


In [20]:
a = tf.constant(10)
b = tf.constant(20)

with tf.Session() as sess:
    result = sess.run(a+b)
    
print(result)

30


In [21]:
const = tf.constant(10)
fill_mat = tf.fill((4,4), 10)
my_zeros = tf.zeros((4,4))
my_ones = tf.ones((4,4))
my_random = tf.random_normal((4,4), mean=0, stddev=1.0)
my_random_u = tf.random_uniform((4,4), minval=0, maxval=1)

In [22]:
my_ops = [const, fill_mat, my_zeros, my_ones, my_random, my_random_u]

In [23]:
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.37098968  0.3845319   1.296093   -0.6971806 ]
 [ 0.85430616  0.35599315 -1.4021785   0.4856331 ]
 [-0.481544    0.1374172   1.5962214  -1.570641  ]
 [ 0.618158   -0.57473046 -0.9591416   0.38302776]]


[[0.45087254 0.98851204 0.89290607 0.13889682]
 [0.65523374 0.23262239 0.5239254  0.31975174]
 [0.11200511 0.2490704  0.6519284  0.9356853 ]
 [0.81946504 0.8702409  0.94764197 0.922215  ]]




In [25]:
a = tf.constant([[1,2], [3,4]])

In [26]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [27]:
b = tf.constant([[10], [100]])

In [28]:
result = tf.matmul(a,b)

In [29]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [30]:
result.eval()

array([[210],
       [430]], dtype=int32)